### PR TITLE
Use classify module from classify_data.ipynb

### PR DESCRIPTION
**Pull request by MBARIMike**
This is the follow-up to our meeting on 12 April 2016. It begins the changes to `classify.py` and the Juypter Notebook so that you can easily do interactive plots. Wait until I make a comment stating it's ready to merge. In the meantime study the code so that you understand all the changes that follow. You may want to `git stash` any local changes you've made before merging to avoid merge conflicts.

### CODE REVIEW

**Comment by MBARIMike** [comment]
@vitoupen @devonrusconi This PR is ready for you to merge. See the rendered Notebook at https://github.com/MBARIMike/stoqs/blob/capstone2016/stoqs/contrib/notebooks/classify_data.ipynb

**Comment by devonrusconi** [comment]
I am still having trouble trying to merge these files. I followed the steps git provided me but it doesn't seem to be working. How would I revert or reset changes? @MBARIMike

**Comment by MBARIMike** [comment]
Can you tell us specifically what you have tried?

**Comment by devonrusconi** [comment]
I tried these commands:

git checkout -b MBARIMike-capstone2016 capstone2016
git pull https://github.com/MBARIMike/stoqs.git capstone2016

git checkout capstone2016
git merge --no-ff MBARIMike-capstone2016
git push origin capstone2016

I also tried to go into the classify.py file and fix the merge errors but I still get the same error of merge conflicts. @MBARIMike

**Comment by MBARIMike** [comment]
I see no commits to your github since 8 April. Have you tried doing `git add ...` and `git commit ...` before doing `git push ...`?

**Pull request closed without merging**
